version: "3"
services:
  device-api:
    image: strapi/strapi
    volumes:
      - ./:/srv/app
    ports:
      - "1337:1337"
    env_file : ".env.db"
  #   depends_on: 
  #     - db

  # db:
  #   image: mysql:5.7.12
  #   command: ["mysqld", "--default-authentication-plugin=mysql_native_password", '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  #   # restart: always
  #   volumes:
  #     - ./data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"  
  #   env_file: ".env.mysql"
    # security_opt:
    #   - seccomp:unconfined

