version: "2.4"
services:
  nginxProxy:
    image: 'jwilder/nginx-proxy'
    container_name: 'nginxProxy'
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/certs:/etc/nginx/certs
      - ./etc/nginx/vhost.d:/etc/nginx/vhost.d
      - ./etc/nginx/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - ./usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    links:
      - adminer:adminer
  nginxLetsencrypt:
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    container_name: 'nginxLetsencrypt'
    restart: unless-stopped
    volumes_from:
      - nginxProxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc/acme.sh:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=letsencrypt@powasert.org
      - LETSENCRYPT_TEST=true
    depends_on:
      - nginxProxy
  db:
    image: mysql
    container_name: powasertDB
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --authentication_policy=mysql_native_password
    restart: always
    env_file: ".env"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    # depends_on:
    #   - nginxLetsencrypt
    volumes:
      - ./data:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
  device-api:
    platform: linux/amd64
    image: arturvoll/deviceapp:1.6
    container_name: 'device-api'
    build: .
    restart: unless-stopped
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./public:/opt/app/public
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
    ports:
      - "1337:1337"
    env_file: ".env"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      # - AUTHENTICATION_DATABASE=${AUTHENTICATION_DATABASE}
      - VIRTUAL_HOST=device-api.powasert.org
      - VIRTUAL_PORT=1337
      - LETSENCRYPT_HOST=device-api.powasert.org
      - LETSENCRYPT_EMAIL=letsencrypt@powasert.org
    command: [ yarn, develop ]
    links:
      - db:db
    depends_on:
      - nginxLetsencrypt
